### ISSUE TITLE
Back End - Script for reading game data

### ISSUE THREAD

**Issue by 7h1nk3r** [SMUArcadeMachine/ManagementConsole#36]
scraper based on outline we will be receiving from SFTW group

**Comment by DejayJD** [comment]
Currently there are two script? Both give errors. Not sure what the issue is. Needs to be tested, either with the UI or with Postman.

**Comment by Toosick** [comment]
Oh boy. This is why I setup Xdebug. Use it. If you don't, ask me. DO NOT USE POSTMAN.

**Comment by Toosick** [comment]
Read the slack message about this.
